### PR TITLE
Fix Crash with district list bounds

### LINKED ISSUE #667: HomeActivity java.lang.ArrayIndexOutOfBoundsException
```
java.lang.ArrayIndexOutOfBoundsException: length=8; index=24
	at com.thebluealliance.androidclient.activities.HomeActivity.updateDistrictsYearSelector(HomeActivity.java:326)
	at com.thebluealliance.androidclient.activities.HomeActivity.setupActionBarForDistricts(HomeActivity.java:317)
	at com.thebluealliance.androidclient.activities.HomeActivity.setupToolbarForCurrentMode(HomeActivity.java:238)
	at com.thebluealliance.androidclient.activities.HomeActivity.switchToModeForId(HomeActivity.java:207)
	at com.thebluealliance.androidclient.activities.HomeActivity.lambda$onNavDrawerItemClicked$4(HomeActivity.java:352)
	at com.thebluealliance.androidclient.activities.HomeActivity.access$lambda$4(HomeActivity.java)
	at com.thebluealliance.androidclient.activities.HomeActivity$$Lambda$5.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

Steps to reproduce:

1. Open event view in main activity
2. Switch to a year prior to the introduction of districts (1992 is a nice example)
3. Switch to districts in the nav drawer

When creating the year selector for the districts view, the app attempts to use the existing selected index from the events view, which is a good idea for current years but won't be valid if the year is prior to 2009.

I think the desired behavior should be to maintain the current year when switching modes if possible, or else default to the current year.

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Fixes #667

---
This change is [Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/669)

### CODE REVIEW

File: android/src/main/java/com/thebluealliance/androidclient/activities/HomeActivity.java [hunk 1]
```diff
@@ -312,7 +312,9 @@ private void setupActionBarForDistricts() {
         final Dialog dialog = makeDialogForYearSelection(R.string.select_year, mDistrictsDropdownItems);
 
         mYearSelectorContainer.setOnClickListener(v -> dialog.show());
-        if (mCurrentSelectedYearPosition >= 0 && mCurrentSelectedYearPosition < mEventsDropdownItems.length) {
+        if (mCurrentSelectedYearPosition >= 0
+                && mCurrentSelectedYearPosition < mEventsDropdownItems.length
```
Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/activities/HomeActivity.java]: Technically we don't need this line... but it doesn't do any damage keeping it
