### PR TITLE
Fix Caching Issues

### LINKED ISSUE #546: 2016 Week 0 Not Showing Event Info
Opening that event also causes:

```
02-20 11:39:21.545 23167-23167/? E/tba-android: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                                                    at com.thebluealliance.androidclient.datafeed.combiners.TeamAndEventTeamCombiner.call(TeamAndEventTeamCombiner.java:29)
                                                    at com.thebluealliance.androidclient.datafeed.combiners.TeamAndEventTeamCombiner.call(TeamAndEventTeamCombiner.java:16)
                                                    at com.thebluealliance.androidclient.datafeed.maps.RetrofitResponseMap.lambda$getAndWriteMappedResponseBody$31(RetrofitResponseMap.java:82)
                                                    at com.thebluealliance.androidclient.datafeed.maps.RetrofitResponseMap.access$lambda$1(RetrofitResponseMap.java)
                                                    at com.thebluealliance.androidclient.datafeed.maps.RetrofitResponseMap$$Lambda$3.call(Unknown Source)
                                                    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
                                                    at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe$2.onResponse(RxJavaCallAdapterFactory.java:109)
                                                    at retrofit.OkHttpCall$1.callSuccess(OkHttpCall.java:77)
                                                    at retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:95)
                                                    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
                                                    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                    at java.lang.Thread.run(Thread.java:818)
                                                 Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit.Response.class
                                                    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
                                                    at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe$2.onResponse(RxJavaCallAdapterFactory.java:109) 
                                                    at retrofit.OkHttpCall$1.callSuccess(OkHttpCall.java:77) 
                                                    at retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:95) 
                                                    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168) 
                                                    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                    at java.lang.Thread.run(Thread.java:818) 
```

device-2016-02-20-114021

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Caching is hard...
The issue in the screenshot happened because the original event was deleted on the server and the new response was in OkHttp's cache, but it never registered as needing to update in the app's db. I was able to fix it by clearing my local data, but that's not a scalable solution. So I added a timestamp to the TBAStatus model. We can set a timestamp server side and each app will clear its local cache exactly once after that (tracked via "last clear" timestamp stored in sharedPrefs). We'll also clear the cache on app updates, just to try and avoid things getting stuck in it.

Fixes #546 

[Review on Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/549)

### CODE REVIEW

File: android/src/main/java/com/thebluealliance/androidclient/datafeed/status/TBAStatusController.java [hunk 1]
```diff
@@ -110,6 +117,25 @@ public int getLatestAppVersion() {
...
+        long lastCacheClear = mPrefs.getLong(STATUS_CACHE_CLEAR_KEY, Long.MIN_VALUE);
+        if (status != null
+                && mOkHttpCache != null
+                && (forceClear || lastCacheClear < status.getLastOkHttpCacheClear())) {
+            Schedulers.io().createWorker().schedule(() -> {
+                Log.i(Constants.LOG_TAG, "Clearing OkHttp cache");
+                try {
+                    mOkHttpCache.evictAll();
+                    mPrefs.edit()
+                            .putLong(STATUS_CACHE_CLEAR_KEY, System.currentTimeMillis() / 1000l)
```
Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/datafeed/status/TBAStatusController.java]: I read the number as "10001" at first glance. Probably best to use a capital L to avoid the 1/l ambiguity in monospace font.

Comment (phil-lopreiato) [inline android/src/main/java/com/thebluealliance/androidclient/datafeed/status/TBAStatusController.java]: Good call, will update
