### PR TITLE
Moar null checks

### LINKED ISSUE #599: NotificationSettingsActivity NullPointerException
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.setEnabled(boolean)' on a null object reference
	at com.thebluealliance.androidclient.activities.settings.NotificationSettingsActivity$NotificationSettingsFragment$1.onPreferenceChange(NotificationSettingsActivity.java:61)
	at android.preference.Preference.callChangeListener(Preference.java:1098)
	at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:64)
	at android.preference.Preference.performClick(Preference.java:1153)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:225)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1166)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
	at android.widget.AbsListView$3.run(AbsListView.java:3943)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5912)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Fixes #599

[Review on Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/613)

### CODE REVIEW

File: android/src/main/java/com/thebluealliance/androidclient/activities/settings/NotificationSettingsActivity.java [hunk 1]
```diff
@@ -51,18 +52,19 @@ public void onCreate(Bundle savedInstanceState) {
...
-                public boolean onPreferenceChange(Preference preference, Object newValue) {
-                    boolean value = (Boolean) newValue;
-                    notificationTone.setEnabled(value);
-                    notificationVibrate.setEnabled(value);
-                    if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
+            enableNotifications.setOnPreferenceChangeListener((preference, newValue) -> {
+                boolean value = (Boolean) newValue;
+                notificationTone.setEnabled(value);
+                notificationVibrate.setEnabled(value);
+                if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
```
Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/activities/settings/NotificationSettingsActivity.java]: Could probably take out this `if`; the null checks will take care of the case where these preferences don't exist on Lollipop devices

Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/activities/settings/NotificationSettingsActivity.java]: Related: I think it's semantically nicer if the version checks are >= LOLLIPOP instead of > KITKAT. Maybe change that as long as we're modifying this file?

Comment (phil-lopreiato) [inline android/src/main/java/com/thebluealliance/androidclient/activities/settings/NotificationSettingsActivity.java]: Fair enough
