### PR TITLE
Fix #591 Boldify followed teams in notifications

### LINKED ISSUE #591: Rich Text In Notifications
Broken off from #583 

> Notifications like "Teams *111*, 222, and 3333 scored 176 vs. 444, 555, and 6666 scored 88" would benefit greatly from bolding the team numbers that you're following. Is bold achievable in a notification?

.

> It looks like we have limited control over how notification text is styles, so bolding should be possible: http://stackoverflow.com/questions/23917127/how-to-highlight-left-hand-side-text-of-every-line-in-notification

### PR DESCRIPTION
**Pull request by 1fish2**
Make the notification bodies a bit more concise and the level-starting title a bit more informative.

Update README.md.

Consistently declare the *.ViewHolder inner classes as static.

Make the notification scripts executable and make “test_notification.py spam” not raise ValueError("sample larger than population”).

QUESTION: What’s the relationship between “favorites” and “team subscriptions”?

QUESTION: Should followsTeam() discard any letter suffix from the teamNumber string?

Tested in a debug build by using Stetho + Chrome Dev Tools to insert some rows into the DB, e.g.:

    INSERT INTO favorites ("key", "userName", "modelKey", "model_enum")
    VALUES ("first.last@gmail.com:frc971", "first.last@gmail.com",
    "frc971", 10)

    INSERT INTO subscriptions ("key", "userName", "modelKey", "model_enum",
    "settings") VALUES ("first.last@gmail.com:frc230",
    "first.last@gmail.com", "frc230", 10, "[match_score, upcoming_match]")

[Review on Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/607)

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
> QUESTION: What’s the relationship between “favorites” and “team subscriptions”?

Push notifications are only sent to teams you have "Subscribed" to. "Favorites" are only for saving a reference for later. This PR only cares about Subscriptions.

> QUESTION: Should followsTeam() discard any letter suffix from the teamNumber string?

Letter suffixes denote "multi-team keys", for example if one team plays multiple robots at an offeason event. I think it's safe to discard them, so following "frc254" also implicitly follows "frc254a"

**Comment by fangeugene** [comment]
This is the verbiage I'm using on the website:

"Favorites are used for personalized content and quick access.
Subscriptions are used for push notifications."

File: android/src/main/java/com/thebluealliance/androidclient/Utilities.java [hunk 1]
```diff
@@ -1,31 +1,36 @@
 package com.thebluealliance.androidclient;
 
+import com.google.common.base.Predicate;
+
+import com.thebluealliance.androidclient.activities.GamedayActivity;
```
Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/Utilities.java]: We need to figure out how we want autoformat to sort imports and make everyone set that as the default so we don't keep getting these changes

**Comment by 1fish2** [comment]
Got it. I'll make the code ignore the favorites table and drop any letter suffix.

File: android/src/main/java/com/thebluealliance/androidclient/Utilities.java (hunk 1 above)
Comment (1fish2) [inline android/src/main/java/com/thebluealliance/androidclient/Utilities.java]: Yes. Would autoformatting all source files make those changes stop?

File: scripts/test_notification.py [hunk 2]
```diff
@@ -228,7 +228,7 @@ def event_down_command(data=event_down_sample):
 
 def spam_command(count=10):
     commands = get_notification_commands()
-    commandsToRun = random.sample(commands, count) 
+    commandsToRun = random.sample(commands, min(count, len(commands)))
```
Comment (nwalters512) [inline scripts/test_notification.py]: As long as you're fixing this (nice catch, btw), `commandsToRun` should probably be generated with `random.choice()` in a loop so that this will work as expected for large values of `count`

File: android/src/main/java/com/thebluealliance/androidclient/Utilities.java (hunk 1 above)
Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/Utilities.java]: Once we decide on the "proper" order and have everyone set it, yeah, that would be a good PR to do.

Comment (phil-lopreiato) [inline android/src/main/java/com/thebluealliance/androidclient/Utilities.java]: You can import the project style file: https://github.com/the-blue-alliance/the-blue-alliance-android#code-style

File: android/src/main/res/values/strings_notification.xml [hunk 3]
```diff
@@ -11,40 +11,32 @@
...
-    <string name="notification_score_teams_lost">%1$s: %2$s lost in %3$s with a score of %4$s.</string>
-    <!-- Example: Midwest Regional: 111 and 1114 tied with the opposing alliance in Quals 32 with a score of 42 - 42. -->
-    <string name="notification_score_teams_tied">%1$s: %2$s tied with the opposing alliance in %3$s with a score of %4$s.</string>
-    <!-- Example: Midwest Regional: 111 and 1114 beat 564 in Quals 32 with a score of 324 - 42. -->
-    <string name="notification_score_teams_beat_teams">%1$s: %2$s beat %3$s in %4$s with a score of %5$s.</string>
-    <!-- Example: Midwest Regional: 111 and 1114 tied with the opposing alliance in Quals 32 with a score of 42 - 42. -->
-    <string name="notification_score_teams_tied_with_teams">%1$s: %2$s tied with %3$s in %4$s with a score of %5$s.</string>
+    <!-- Example: Midwest Regional Quals 32: 111, 971, 1114 beat 254, 118, 1983 scoring 324-42. -->
+    <string name="notification_score_teams_beat_teams">^1 ^2: ^3 beat ^4 scoring ^5.</string>
+    <!-- Example: Midwest Regional Quals 32: 111, 971, 1114 tied 254, 118, 1983 scoring 324-324. -->
```
Comment (nwalters512) [inline android/src/main/res/values/strings_notification.xml]: `tied` is certainly concise, but I think `tied with` reads better

File: android/src/main/java/com/thebluealliance/androidclient/Utilities.java (hunk 1 above)
Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/Utilities.java]: Didn't realize import order was specified there, nice!

File: scripts/test_notification.py (hunk 2 above)
Comment (1fish2) [inline scripts/test_notification.py]: Will do.

File: android/src/main/res/values/strings_notification.xml (hunk 3 above)
Comment (1fish2) [inline android/src/main/res/values/strings_notification.xml]: OK.

**Comment by nwalters512** [comment]
LGTM. I love the simplified notification bodies, should be much easier to parse quickly.

File: android/src/main/java/com/thebluealliance/androidclient/Utilities.java (hunk 1 above)
Comment (1fish2) [inline android/src/main/java/com/thebluealliance/androidclient/Utilities.java]: Yes, that code-style file performed these import changes. I added a note in the README about where to install that file on OSX.

**Comment by 1fish2** [comment]
> Some checks haven’t completed yet
> 1 pending and 1 successful checks

Is that normal? Wait for it?

Screen shots:
upcoming-match
match-score
5-levels-starting

**Comment by phil-lopreiato** [comment]
Reviewed 24 of 29 files at r1, 8 of 8 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[android/src/main/java/com/thebluealliance/androidclient/Utilities.java, line 363 \[r3\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607#-KCE4wFCGFD1DjKgcABI:-KCE4wFCGFD1DjKgcABJ:-564505696) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/f36df0d5db2de0d65c607a4336258ea82f451235/android/src/main/java/com/thebluealliance/androidclient/Utilities.java#L363)):*
Love this approach!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607)*

**Comment by phil-lopreiato** [comment]
@1fish2 the second check is from reviewable.io which is a service I'm trying for code review: https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/607

Looks good though!

**Comment by 1fish2** [comment]
@phil-lopreiato Piotr will be happy we're using his Reviewable tool. I haven't had the occasion to do much with it yet.

**Comment by 1fish2** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[android/src/main/java/com/thebluealliance/androidclient/Utilities.java, line 363 \[r3\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607#-KCE4wFCGFD1DjKgcABI:-KCEG5HCd7FWP8phJ2Ga:-1167048065) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/f36df0d5db2de0d65c607a4336258ea82f451235/android/src/main/java/com/thebluealliance/androidclient/Utilities.java#L363)):*
:smiley_cat:
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607)*

**Comment by 1fish2** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[android/src/main/java/com/thebluealliance/androidclient/Utilities.java, line 363 \[r3\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607#-KCE4wFCGFD1DjKgcABI:-KCEGPKfP7hBXUVKpthK:976859417) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/f36df0d5db2de0d65c607a4336258ea82f451235/android/src/main/java/com/thebluealliance/androidclient/Utilities.java#L363)):*
Where is the "unresolved discussion"?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607)*

File: android/src/main/java/com/thebluealliance/androidclient/models/Match.java [hunk 4]
```diff
@@ -152,6 +155,29 @@ public static JsonArray getBlueTeams(JsonObject alliances) {
         return getBlueAlliance(alliances).getAsJsonArray("teams");
     }
 
+    /** @return team keys from {@link #getRedTeams} or {@link #getBlueTeams}. */
+    @NonNull
+    public static ArrayList<String> teamKeys(JsonArray teamsJson) {
+        ArrayList<String> teamKeys = new ArrayList<>();
```
Comment (1fish2) [inline android/src/main/java/com/thebluealliance/androidclient/models/Match.java]: It could set the ArrayList capacity. Worth changing?

File: android/src/main/java/com/thebluealliance/androidclient/models/Match.java [hunk 5]
```diff
@@ -152,6 +155,29 @@ public static JsonArray getBlueTeams(JsonObject alliances) {
...
+            teamKeys.add(teamsJson.get(i).getAsString());
+        }
+        return teamKeys;
+    }
+
+    /** @return team number strings from {@link #getRedTeams} or {@link #getBlueTeams}. */
+    @NonNull
+    public static ArrayList<String> teamNumbers(JsonArray teamsJson) {
+        ArrayList<String> teamKeys = teamKeys(teamsJson);
+        ArrayList<String> teamNumbers = new ArrayList<>();
```
Comment (1fish2) [inline android/src/main/java/com/thebluealliance/androidclient/models/Match.java]: Ditto.

**Comment by phil-lopreiato** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[android/src/main/java/com/thebluealliance/androidclient/models/Match.java, line 161 \[r3\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607#-KCD3k8gYEa-jCvFwMVd-r3-161:-KCHW7fK4pcyxCOCfpLU:-2129318954) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/f36df0d5db2de0d65c607a4336258ea82f451235/android/src/main/java/com/thebluealliance/androidclient/models/Match.java#L161)):*
Yeah, that's a smart change since there is a known size (3)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607)*

File: android/src/main/java/com/thebluealliance/androidclient/models/Match.java (hunk 4 above)
Comment (phil-lopreiato) [inline android/src/main/java/com/thebluealliance/androidclient/models/Match.java]: Shoot, forgot reviewable doesn't reply inline. Yeah, that's a good change

**Comment by phil-lopreiato** [comment]
I'll do a merge-a-thon tonight and get everything prepped for shipping on Wednesday. Sorry for the delay

**Comment by 1fish2** [comment]
Review status: 32 of 34 files reviewed at latest revision, 2 unresolved discussions.

---

*[android/src/main/java/com/thebluealliance/androidclient/models/Match.java, line 161 \[r3\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607#-KCD3k8gYEa-jCvFwMVd-r3-161:-KCHqimbHhksXyzvOuc_:-46367540) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/f36df0d5db2de0d65c607a4336258ea82f451235/android/src/main/java/com/thebluealliance/androidclient/models/Match.java#L161)):*
Done.

[I wished Java 1 had closures. Then we'd just map a closure over the collection. Future Android on Java 8 will have streams, but it's still more complicated than collection.map(lambda).]

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607)*

**Comment by phil-lopreiato** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607)*

File: android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java [hunk 6]
```diff
@@ -80,6 +86,25 @@ private void getComponenet() {
...
 
+    /**
+     * Checks if the user subscribes to the given team. Implements FollowsChecker.
+     *
+     * @param teamNumber the team number without the "frc" prefix.
+     * @param notificationType one of NotificationTypes.UPCOMING_MATCH, MATCH_SCORE, ...
+     */
+    public boolean followsTeam(Context context, String teamNumber, String notificationType) {
+        String currentUser = AccountHelper.getSelectedAccount(context);
+        String teamKey = TeamHelper.baseTeamKey("frc" + teamNumber);
```
Comment (phil-lopreiato) [inline android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java]: There's one case you missed here. You'll also need to account for Team@Event subscriptions. The model key is of the format `2015onwa_frc1114`

**Comment by 1fish2** [comment]
Review status: 30 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java, line 97 \[r4\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607#-KCD3k8f2IHLxGrB26Vb-r4-97:-KCJn7JDoO4bQ3pgDZAi:815176430) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/25cc3e3a6e7ecde199dc236db408d54245e96293/android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java#L97)):*
Aha!
Done.

---

*[android/src/main/java/com/thebluealliance/androidclient/models/Match.java, line 173 \[r3\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607#-KCD3k8gYEa-jCvFwMVd-r3-173:-KCHrGk1i7fgirnKtieS:-499146009) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/f36df0d5db2de0d65c607a4336258ea82f451235/android/src/main/java/com/thebluealliance/androidclient/models/Match.java#L173)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607)*

**Comment by phil-lopreiato** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/607)*
