### PR TITLE
Match List Fixes

### LINKED ISSUE #600: MatchListAdapter IndexOutOfBoundsException
```
java.lang.IndexOutOfBoundsException: Invalid index 12, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.thebluealliance.androidclient.adapters.MatchListAdapter.getChildView(MatchListAdapter.java:37)
	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:451)
	at android.widget.AbsListView.obtainView(AbsListView.java:2389)
	at android.widget.ListView.makeAndAddView(ListView.java:1878)
	at android.widget.ListView.fillDown(ListView.java:705)
	at android.widget.ListView.fillGap(ListView.java:669)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5320)
	at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3567)
	at android.widget.AbsListView.onTouchMove(AbsListView.java:4015)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3815)
	at android.view.View.dispatchTouchEvent(View.java:9297)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2549)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2445)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent_aroundBody0(PhoneWindow.java:1756)
	at com.android.internal.policy.PhoneWindow$AjcClosure1.run(PhoneWindow.java:1)
	at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$2$99ce526bproceed(PhoneWindowAO.aj:113)
	at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$2$99ce526b(PhoneWindowAO.aj:117)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1756)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2800)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2406)
	at android.view.View.dispatchPointerEvent(View.java:9517)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4309)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4175)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3682)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3735)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3701)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3709)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3682)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3735)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3701)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3828)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3709)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3885)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3682)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3735)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3701)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3709)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3682)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6001)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5975)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5936)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6133)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6083)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6156)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:600)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5525)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

### LINKED ISSUE #606: Live Events Elim Sort Wrong
It should sort by play order when the event is live, and display order otherwise. 

This also affects the last/next match display on the info tab. 

Will update with screenshot when not on mobile 

screenshot_20160306-142643

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Fixes #606 and updates test suite. Also fixes #600 

[Review on Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/611)

### CODE REVIEW

File: android/src/main/java/com/thebluealliance/androidclient/adapters/MatchListAdapter.java [hunk 1]
```diff
@@ -34,6 +34,11 @@ public void setTeamKey(String teamKey) {
 
     @Override
     public View getChildView(int groupPosition, int childPosition, boolean isLastChild, View convertView, ViewGroup parent) {
+        if (groupPosition >= mGroups.size()
```
Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/adapters/MatchListAdapter.java]: It's good that we do a bounds check, but it's weird that we'd get into this situation in the first place. Is this worth looking deeper into?

File: android/src/main/java/com/thebluealliance/androidclient/models/Match.java [hunk 2]
```diff
@@ -356,7 +357,6 @@ public MatchListElement render(boolean showVideo, boolean showHeaders, boolean s
         try {
             videos = getVideos();
         } catch (FieldNotDefinedException e) {
-            Log.w(Constants.LOG_TAG, "Required field for match render: Database.Matches.VIDEOS. Defaulting to none.");
```
Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/models/Match.java]: Weird request... can we leave this in for now? Eventually I'll see this span from the ticker fragment and have the time to get to the bottom of the performance issue with the ticker rendering (even if this isn't the root of the performance problem) :stuck_out_tongue:

File: android/src/main/java/com/thebluealliance/androidclient/adapters/MatchListAdapter.java (hunk 1 above)
Comment (phil-lopreiato) [inline android/src/main/java/com/thebluealliance/androidclient/adapters/MatchListAdapter.java]: I tried to find the root cause and couldn't get anywhere. You want to give it a shot?

I figure we'll come across it in the future, it'll still be obvious when it happens, just won't crash

File: android/src/main/java/com/thebluealliance/androidclient/models/Match.java (hunk 2 above)
Comment (phil-lopreiato) [inline android/src/main/java/com/thebluealliance/androidclient/models/Match.java]: I think this is partially slowing down the renders (lots of logging is slow) and causing frame drops, since this is done all on the UI thread.

I can put it back and make it log.d so it doesn't affect prod though

Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/models/Match.java]: Sounds good.

File: android/src/main/java/com/thebluealliance/androidclient/adapters/MatchListAdapter.java (hunk 1 above)
Comment (nwalters512) [inline android/src/main/java/com/thebluealliance/androidclient/adapters/MatchListAdapter.java]: I'll file a new issue so I don't forget to check this out in the future. This is a good enough fix for now; I'd rather have sketchy rendering behavior than crashes!
