### PR TITLE
Fix #387 Incorrect team@event Summary Alliance Determination

### LINKED ISSUE #387: Possible Incorrect team@event Summary Alliance Determination
From comments on 9d7256f3ffb0c53174aebe38074e9acf8a3c19a (https://github.com/the-blue-alliance/the-blue-alliance-android/commit/9d7256f3ffb0c53174aebe38074e9acf8a3c19af#commitcomment-10676779)

### PR DESCRIPTION
**Pull request by 1fish2**
Refactor out Match hasTeam() to apply the fix everywhere.

Refactor out red/blue alliance/teams/score getters. (I almost made them instance methods but adjusting the exception-handling code would not be as local.)

Use the existing Match#hasBeenPlayed() method.

### CODE REVIEW

File: android/src/test/java/com/thebluealliance/androidclient/test/models/MatchTest.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+/**
+ * Created by Jerry on 4/15/2015.
+ */
+@RunWith(RobolectricTestRunner.class)
+public class MatchTest {
+    private static final String ALLIANCES_2009 = "{" +
+            "\"red\":  {\"score\": 81, \"teams\": [\"frc68\", \"frc217\", \"frc247\"]}," +
+            "\"blue\": {\"score\": 98, \"teams\": [\"frc111\", \"frc971\", \"frc67\"]}" +
+            "}";
+    private static final JsonObject ALLIANCES = new JsonParser().parse(ALLIANCES_2009).getAsJsonObject();
```
Comment (phil-lopreiato) [inline android/src/test/java/com/thebluealliance/androidclient/test/models/MatchTest.java]: You can do this in a [@Before](http://junit.sourceforge.net/javadoc/org/junit/Before.html) annotated method to make sure done right before each test has been run.

**Comment by phil-lopreiato** [comment]
Looks good! It doesn't really matter if you move the tests to a before annotated method (I personally think it's cleaner, but it'll work either way) - let me know which you'd like to do and I'll merge when you're ready

File: android/src/test/java/com/thebluealliance/androidclient/test/models/MatchTest.java (hunk 1 above)
Comment (1fish2) [inline android/src/test/java/com/thebluealliance/androidclient/test/models/MatchTest.java]: Since JsonObject is mutable, it'd be better to create it in a @Before method. I'll do that now.

**Comment by 1fish2** [comment]
Ready.

**Comment by phil-lopreiato** [comment]
:+1:
